### PR TITLE
Add RemoveRows() to Table

### PR DESCRIPTION
**Pull request by meain**

### CODE REVIEW

**Comment by marcusolsson** [comment]
Hey @meain, thanks for your PR! I think it makes sense and I think it fits in well with the other widgets, for example, I could easily see a `RemoveRow(i int)` as well to match the `List` widget! 

I will test this out after work later today!

**Comment by meain** [comment]
What is your opinion on making `RemoveRows` accept variable arguments?
```go
RemoveRows(values ...int) error {
    startIndex := values[0]
    numberOfElementsToRemove := values[1]
}
```
* splice the array using these
* if nothing in values, remove all
* if only `startIndex` remove everything from there
* return `error` in case they pass in more arguments

**Comment by marcusolsson** [comment]
Hm, I think it probably wouldn't be what you would expect as a new user. I think `RemoveRow(i int)` is a simpler way to accomplish this, and it would enable users to write their own helper function for splicing the grid/table.

**Comment by marcusolsson** [comment]
This should probably be a method on `Grid` so that both widgets can benefit. In `Table` you would then do something like:

```
func (t *Table) RemoveRows() {
	t.Grid.RemoveRows()
	t.selected = -1
}
```

What do you think?

**Comment by meain** [comment]
Sound cool, I will make that change. 👌

**Comment by marcusolsson** [comment]
Great! I think `RemoveRows()` will be just fine, that way it's consistent with https://github.com/marcusolsson/tui-go/blob/master/list.go#L106-L114.

**Comment by meain** [comment]
For some reason I can't wrap my head around how `image.Point` works.
```go
func (g *Grid) RemoveRow(index int) {
	g.rows--
	delete(g.cells, image.Point{<loop? idk>, index})
}
```

How should I be doing the delete in grid.go for a single element?

**Comment by marcusolsson** [comment]
I think you're on the right track. You'd want to loop from `0` to `g.cols` and delete the cells with the key `image.Point{x, index}` (or `image.Pt(x, index)`). We probably also need to make sure that a row with that index exists before decrementing the row number, to make sure we don't get a negative row number. Might be a good thing to create a test for?

**Comment by meain** [comment]
@marcusolsson I guess it is good now

**Comment by marcusolsson** [comment]
Looks good to me! Thanks so much!

**Pull request merged**
