### PR TITLE
Fix selection change on SetSelected for List and also check for the selection func in Table's

### PR DESCRIPTION
**Pull request by gonzaloserrano**
tests pass so I didn't bother to check them sorry ;-)

### CODE REVIEW

**Comment by marcusolsson** [comment]
Well spotted :) When I wrote selection for `Table` the idea was to have the `Select` method for selecting _and_ invoking the callback, and the `SetSelected` in cases where you want to update the view _without_ invoking the callback.  

First suggestion would be to keep the `Table` and `List` selection APIs consistent (by adding the corresponding `Select` method for `List`). 

Alternatively, I'll be ready to acknowledge that separating the two methods might be the work of over-design from my part :-) If you think one of them should be dropped, I vote to keep `Select`.

I'll be fine with whichever option you think is appropriate :)

**Comment by gonzaloserrano** [comment]
You are right, I missed the difference between `Selected`/`SetSelected`. I just need the former but I see both cases could be interesting so I'll go for your first suggestion.

**Comment by gonzaloserrano** [comment]
Fixed.

**Comment by marcusolsson** [comment]
Looks great! Thank you very much! 👍

**Pull request merged**
