### PR TITLE
True color support

### PR DESCRIPTION
**Pull request by d3nw0**
My [old](https://github.com/marcusolsson/tui-go/pull/95) pull request contained bad code and failed tests. This is a better version of it that will not break old code.

### CODE REVIEW

**Comment by cceckman** [comment]
Suggestion (which could go in a followup PR): Rather than having a new type and a switch statement, 
```
type Color tcell.Color
const (
  ColorYellow Color = tcell.ColorYellow
  ...
)
```

(and corresponding other changes).

That means that you don't have to import `tcell` to get the standard ~8 colors if you already have `tui` around, but removes a translation layer. It's also a little clearer as to where to find more information.

**Comment by marcusolsson** [comment]
The switch is a remnant from when tui supported both termbox and tcell. Now that we're only supporting tcell, I think it's safe to rewrite it like @cceckman hinted. I'd like to avoid users having to import tcell at all, and would rather mirror the color set from tcell. Type aliases might be more convenient here(?) but that would require >=go1.8.

**Comment by d3nw0** [comment]
I would suggest removing the color constant variables, and using `tui.GetColor(name string) Color`, which has more color coverage.

**Comment by cceckman** [comment]
Devil's advocate: Strings are not type-safe, enums are. `tui.GetColor("fuschia")` vs. `tui.GetColor("fucshia")` is a runtime error, while `tui.ColorFuschia` vs. `tui.ColorFucshia` is a compile-time error.

It would be useful to have a string-based variant - for cases where the color is a user input - but I that's not always.

**Comment by d3nw0** [comment]
Yes, but in-case the string is misspelled the default color will be [returned](https://github.com/gdamore/tcell/blob/master/color.go#L1018). That way a runtime error will not exist.

**Pull request merged**
