### PR TITLE
Scroll list position

### PR DESCRIPTION
**Pull request by williamsharkey**
The list pos(ition) variable seemed to not effect anything. 

I think it was intended for scrolling the list.

I made it implement scrolling.

The mutating of pos is done in the draw routine, so that it works properly when resizing the window, etc.

### CODE REVIEW

**Comment by williamsharkey** [comment]
The pull didn’t build because of some irrelevant issue with one of the dependencies of the build checks:

The command "go get honnef.co/go/tools/cmd/megacheck" failed and exited with 1 during 

I can’t find a megacheck for in honnef’s repo. Maybe it was moved or renamed.  Kind of annoying to find because the last working build was months ago. It would be nice if CI would auto rebuild known passing builds to notify you when something breaks. I will investigate some more.

**Comment by williamsharkey** [comment]
Around May 30th, megacheck was removed from go-tools:

megacheck history: 
https://github.com/dominikh/go-tools/commits/master/cmd/megacheck

Some explanation appears here:
https://github.com/dominikh/go-tools/commit/a1e48607f5793ffdd412cda1337fe21b2b6823fa#diff-2a2af5b3ecc1d00b6a5b50cd14bd428e

I think now we are supposed to run staticcheck. I'm assuming that by default it runs similar checks as megacheck did, but not sure. there is a flag -checks to specify the checks manually.  
https://staticcheck.io/docs/

I would try to fix this issue myself but I don't have access to the Travis CI configurations.

**Comment by williamsharkey** [comment]
I pulled too many changes into this pull request. I only wanted to request changes I made to list.go, not everything else.

**Comment by marcusolsson** [comment]
Hey, I'm not maintaining this repository anymore, but I'll see if I can fix the dependency issues so that we can look at merging you fix :)

**Pull request closed without merging**
