### PR TITLE
Export user callback submission

### PR DESCRIPTION
**Pull request by heavenlyhash**
This is a patch attempting to address https://github.com/marcusolsson/tui-go/issues/34 .  WDYT? :)

### CODE REVIEW

**Comment by heavenlyhash** [comment]
It's possible the `Repaint` var is no longer necessary and could be removed, but I haven't yet attempted that here.

**Comment by marcusolsson** [comment]
I've been waiting for this issue to pop up and have been dreading adding mutexes all over. This is a very nice and simple alternative! :+1:  I do believe this removes the need for the `Repaint` (which I'm not overly proud about) and I don't mind if we remove it completely with this fix.

What do you think about renaming `QueueUpdate` to `RequestUpdate`, as the queue is somewhat of an implementation detail?

Can't wait to merge this :)

**Comment by heavenlyhash** [comment]
I waffled on the name a lot!  (I always waffle on names a lot.)  Maybe even just `Update`?

While that rename sounds fine to me, the queue implementation detail does somewhat leak I think, for the record.  The `{Queue/Request/?}Update` method can (and probably will?) return before the user's function is called and before the repaint is finished.  I can't really think of a case this would matter much in practice though.  (If we ever find one, we can just add a `SynchronousUpdate` method later, which uses a `struct{func(), sync.WaitGroup}` and blocks itself until the tui event loop done's the waitgroup.)

**Comment by marcusolsson** [comment]
Good points! I'm happy going with just `Update` for now, possibly with a matching synchronous method down the road :+1:

**Comment by heavenlyhash** [comment]
Added commits: Renamed, and I lunged for the synchronous func too!

**Comment by marcusolsson** [comment]
Hah, nice lunge! 

For the initial release though, I want to try to keep the API as slim as possible. I like the idea of a synchronous update but I can't think of a concrete use-case for it right now.

Unless you have an example of when you'd need a synchronous update, would you mind if we hold the last commit off for now?

**Comment by heavenlyhash** [comment]
I had been toying with the idea that the `Update` func, since it's already async, might be in the future amended to say it might do batched/debounced operation?  But that is not today, so...

Popped that last commit back off this branch.  (I left it in branch 'synchronous-update' in my fork if you want to fetch it again later ¯\_(ツ)_/¯)

**Comment by marcusolsson** [comment]
Really appreciate it, I'll be sure to give you a nudge when the case is stronger! 

Thank you so much for your contribution, both code and discussion! 👍

**Comment by heavenlyhash** [comment]
:+1: you know penance for being so awesome on response time is going to be a bunch more PRs for widgets and stuff in the future, right? :D  Thanks!

**Pull request merged**
