### PR TITLE
Add scroll area

### LINKED ISSUE #40: Scroll area support
Tables with too many rows will not fit. When a row outside view is selected the scroll area should offset the view to include the selected row.

For comparison: Qt has a [QScrollArea](http://doc.qt.io/qt-4.8/qscrollarea.html) that decorates a widget with scrolling functionality.

This would be very nice combined with mouse support :)

Example: 

```go
t := tui.NewTable(0,0)
a := tui.NewScrollArea(t)
```

### PR DESCRIPTION
**Pull request by marcusolsson**
I think I finally got this nailed down. Issues were mostly related to masking rather than the scroll area itself. More specifically due to not having clearly defined what a zero mask meant.

A key insight was to make sure that a mask needs to be defined at the root level, based on the size of the Surface.

Closes #40.

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
Sweet. I'll do some testing tonight.

**Comment by cornfeedhobo** [comment]
The only thing I see is the removal of SizeHint(). This defaults to the WidgetBase one, which returns image.ZP. In my testing this means my scroll area is very small and does not expand properly.

Also, would you be open to a PR for this branch to include scroll direction support, before merging to master?

Thanks!

**Comment by marcusolsson** [comment]
@cornfeedhobo Thanks for the heads up about SizeHint! Cleaned up the example as well. I'd love to get your changes as well!

**Comment by marcusolsson** [comment]
Hm, right. Now I remember why I removed the `SizeHint`. Currently, I'm using the underlying widget's `SizeHint`, which means that even though the widget is scrolled out of the view, the scroll area will have the size of the widget. Feels wrong, although I'm not sure it is.

**Comment by cornfeedhobo** [comment]
Ah! Yes, I am seeing this same issue. Hmm, I'll think about this one too.

**Comment by marcusolsson** [comment]
After giving this some thought, I think it's unwise to use the underlying widget's size hint for the scroll area. I don't think we can define a good preferred size of a scroll area. After looking at the Qt implementation, which seems to return a hard-coded size of [256, 192], I think we could set a default size of the scroll area and later on maybe even make it customizable.

**Comment by marcusolsson** [comment]
@cornfeedhobo Merging this now but please feel free to send a separate PR with the scroll direction support!

**Comment by cornfeedhobo** [comment]
Will do. Sorry heads down on something but will circle back to this. Thanks!

**Pull request merged**
