### PR TITLE
add box.Length

### PR DESCRIPTION
**Pull request by taylorchu**
add box length, and fix boundary checking for insert and remove

### CODE REVIEW

**Comment by taylorchu** [comment]
@marcusolsson

**Comment by marcusolsson** [comment]
Hm, interesting. The build succeeded on Go 1.8 and 1.9 but fails on tip. I'll see if I can figure out why. Other than that, I see no issues with this! Thanks!

**Comment by taylorchu** [comment]
It seems like it fails at deps fetching. I restarted the tests, and now it's fine.

**Comment by marcusolsson** [comment]
Merged! Thank you!

**Pull request merged**
